name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3 # Updated to v3

      - name: Set up Python
        uses: actions/setup-python@v4 # Updated to v4
        with:
          python-version: "3.x"

      - name: Install PDM
        run: python -m pip install pdm

      - name: Install dependencies
        run: pdm install

      - name: Bump version
        run: |
          pdm bump --patch  # Change to --minor or --major depending on the release type
          git add pyproject.toml
          git commit -m "Bump version to ${{ github.ref_name }}"
          git push origin main

      - name: Build package
        run: pdm build
